services:
  batch-server:
    build:
      context: .
      dockerfile: ./images/dev/apps/batch/Dockerfile
    volumes:
      # - ./go.mod:/user/src/app/go.mod
      # - ./go.sum:/user/src/app/go.sum
      - ./apps/batch:/usr/src/app/apps/batch
      - ./internal:/usr/src/app/internal
    ports:
      - "8000:8000"
    tty: true
    networks:
      - financial-bot-network
    depends_on:
      - etcd1
      - etcd2
      - postgres
      - migration

  etcd1:
    image: bitnami/etcd:3.5.9
    restart: always
    environment:
      - ETCD_NAME=etcd1
      - ETCD_INITIAL_ADVERTISE_PEER_URLS=http://etcd1:12380
      - ETCD_LISTEN_PEER_URLS=http://0.0.0.0:12380
      - ETCD_LISTEN_CLIENT_URLS=http://0.0.0.0:12379
      - ETCD_ADVERTISE_CLIENT_URLS=http://etcd1:12379
      - ETCD_INITIAL_CLUSTER=etcd1=http://etcd1:12380,etcd2=http://etcd2:22380
      - ETCD_INITIAL_CLUSTER_TIMEOUT=5000
      - ETCD_INITIAL_CLUSTER_STATE=new
      - ETCD_ROOT_PASSWORD=""
      # - ALLOW_NONE_AUTHENTICATION=yes
    volumes:
      - ./tmp/etcd1:/bitnami/etcd
    ports:
      - 12379:12379
    networks:
      - financial-bot-network

  etcd2:
    image: bitnami/etcd:3.5.9
    restart: always
    environment:
      - ETCD_NAME=etcd2
      - ETCD_INITIAL_ADVERTISE_PEER_URLS=http://etcd2:22380
      - ETCD_LISTEN_PEER_URLS=http://0.0.0.0:22380
      - ETCD_LISTEN_CLIENT_URLS=http://0.0.0.0:22379
      - ETCD_ADVERTISE_CLIENT_URLS=http://etcd2:22379
      - ETCD_INITIAL_CLUSTER=etcd1=http://etcd1:12380,etcd2=http://etcd2:22380
      - ETCD_INITIAL_CLUSTER_TIMEOUT=5000
      - ETCD_INITIAL_CLUSTER_STATE=new
      - ETCD_ROOT_PASSWORD=""
      # - ALLOW_NONE_AUTHENTICATION=yes
    volumes:
      - ./tmp/etcd2:/bitnami/etcd
    ports:
      - 22379:22379
    networks:
      - financial-bot-network

  postgres:
    image: postgres:16.0
    restart: always
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - PGUSER=postgres
      - TZ=Asia/Tokyo
    ports:
      - 5432:5432
    volumes:
      - ./tmp/postgresql/data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-q", "-U", "${POSTGRES_USER}", "-d", "${POSTGRES_DB}"]
      interval: 1s
      timeout: 1s
      retries: 5
    networks:
      - financial-bot-network

  migration:
    image: yoshi429/goose-migration:0.0.3
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./db/migrations:/go/src/db
    environment:
      - DB_NAME=postgres
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=password
      - DB_SSL=disable
    networks:
      - financial-bot-network

networks:
  financial-bot-network:
    driver: bridge