// Code generated by goctl. DO NOT EDIT.
package types

type UserLoginReq struct {
}

type UserInfoReq struct {
}

type UserLoginResp struct {
}

type UserInfoResp struct {
}

type UserInfoUpdateReq struct {
}

type UserInfoUpdateResp struct {
}

type UserRoleReq struct {
}

type UserRoleResp struct {
}

type UserRoleUpdateReq struct {
}

type UserRoleUpdateResp struct {
}

type UserRoleAddReq struct {
}

type UserRoleAddResp struct {
}

type UserRoleDeleteReq struct {
}

type UserRoleDeleteResp struct {
}

type UserClassReq struct {
}

type UserClassResp struct {
}

type UserClassUpdateReq struct {
}

type UserClassUpdateResp struct {
}

type UserClassAddReq struct {
}

type UserClassAddResp struct {
}

type UserClassDeleteReq struct {
}

type UserClassDeleteResp struct {
}
