// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.21.0

package model

import (
	"database/sql"
	"time"
)

type News struct {
	ID          int32          `json:"id"`
	Title       string         `json:"title"`
	Description sql.NullString `json:"description"`
	Link        string         `json:"link"`
	Thumbnail   sql.NullString `json:"thumbnail"`
	PublishedAt time.Time      `json:"published_at"`
}
