// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	"github.com/yoshihiro-shu/financial-bot/apps/notification/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/api/v1/health-check",
				Handler: HealthCheckHandler(serverCtx),
			},
		},
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/notification/financial-news",
				Handler: NotificationFinancialNewsHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/notification/stock-info",
				Handler: NotificationStockInfoHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/notification/cypto-currency-info",
				Handler: NotificationCryptoCurrencyInfoHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/v1"),
	)
}
