// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.21.0

package postgresql

import (
	"database/sql"
	"time"
)

type Categories struct {
	ID        int32     `db:"id"`
	Name      string    `db:"name"`
	CreatedAt time.Time `db:"created_at"`
	UpdatedAt time.Time `db:"updated_at"`
}

type DailyStockPrices struct {
	ID         int32     `db:"id"`
	StockID    int32     `db:"stock_id"`
	Date       time.Time `db:"date"`
	OpenPrice  string    `db:"open_price"`
	HighPrice  string    `db:"high_price"`
	LowPrice   string    `db:"low_price"`
	ClosePrice string    `db:"close_price"`
	Volume     int64     `db:"volume"`
}

type News struct {
	ID          int32          `db:"id"`
	Title       string         `db:"title"`
	Description sql.NullString `db:"description"`
	Link        string         `db:"link"`
	Thumbnail   sql.NullString `db:"thumbnail"`
	Score       int32          `db:"score"`
	PublishedAt time.Time      `db:"published_at"`
	CreatedAt   time.Time      `db:"created_at"`
	UpdatedAt   time.Time      `db:"updated_at"`
	ProviderID  sql.NullInt32  `db:"provider_id"`
	CategoryID  sql.NullInt32  `db:"category_id"`
}

type Providers struct {
	ID        int32     `db:"id"`
	Name      string    `db:"name"`
	CreatedAt time.Time `db:"created_at"`
	UpdatedAt time.Time `db:"updated_at"`
}

type Stocks struct {
	ID     int32  `db:"id"`
	Symbol string `db:"symbol"`
	Name   string `db:"name"`
}
