// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.21.0

package postgresql

import (
	"database/sql"
	"time"
)

type News struct {
	ID          int32          `db:"id"`
	Title       string         `db:"title"`
	Description sql.NullString `db:"description"`
	Link        string         `db:"link"`
	Thumbnail   sql.NullString `db:"thumbnail"`
	Score       int32          `db:"score"`
	PublishedAt time.Time      `db:"published_at"`
	CreatedAt   time.Time      `db:"created_at"`
	UdpatedAt   time.Time      `db:"udpated_at"`
}
