// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.21.0
// source: news.sql

package postgresql

import (
	"context"
	"database/sql"
	"time"
)

const createNews = `-- name: CreateNews :one
INSERT INTO news (
  title, description, link, thumbnail, score, published_at, provider_id, category_id
) VALUES (
  $1, $2, $3, $4, $5, $6, $7, $8
)
RETURNING id, title, description, link, thumbnail, score, published_at, created_at, updated_at, provider_id, category_id
`

type CreateNewsParams struct {
	Title       string         `db:"title"`
	Description sql.NullString `db:"description"`
	Link        string         `db:"link"`
	Thumbnail   sql.NullString `db:"thumbnail"`
	Score       int32          `db:"score"`
	PublishedAt time.Time      `db:"published_at"`
	ProviderID  sql.NullInt32  `db:"provider_id"`
	CategoryID  sql.NullInt32  `db:"category_id"`
}

func (q *Queries) CreateNews(ctx context.Context, arg CreateNewsParams) (News, error) {
	row := q.db.QueryRowContext(ctx, createNews,
		arg.Title,
		arg.Description,
		arg.Link,
		arg.Thumbnail,
		arg.Score,
		arg.PublishedAt,
		arg.ProviderID,
		arg.CategoryID,
	)
	var i News
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.Link,
		&i.Thumbnail,
		&i.Score,
		&i.PublishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ProviderID,
		&i.CategoryID,
	)
	return i, err
}

const deleteNews = `-- name: DeleteNews :exec
DELETE FROM news
WHERE id = $1
`

func (q *Queries) DeleteNews(ctx context.Context, id int32) error {
	_, err := q.db.ExecContext(ctx, deleteNews, id)
	return err
}

const getNews = `-- name: GetNews :one
SELECT id, title, description, link, thumbnail, score, published_at, created_at, updated_at, provider_id, category_id FROM news
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetNews(ctx context.Context, id int32) (News, error) {
	row := q.db.QueryRowContext(ctx, getNews, id)
	var i News
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.Link,
		&i.Thumbnail,
		&i.Score,
		&i.PublishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ProviderID,
		&i.CategoryID,
	)
	return i, err
}

const listNews = `-- name: ListNews :many
SELECT id, title, description, link, thumbnail, score, published_at, created_at, updated_at, provider_id, category_id FROM news
ORDER BY published_at
`

func (q *Queries) ListNews(ctx context.Context) ([]News, error) {
	rows, err := q.db.QueryContext(ctx, listNews)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []News{}
	for rows.Next() {
		var i News
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.Link,
			&i.Thumbnail,
			&i.Score,
			&i.PublishedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ProviderID,
			&i.CategoryID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
