// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.21.0
// source: provider.sql

package postgresql

import (
	"context"
)

const createProvider = `-- name: CreateProvider :one
INSERT INTO providers (
    name
) VALUES (
  $1
)
RETURNING id, name, created_at, updated_at
`

func (q *Queries) CreateProvider(ctx context.Context, name string) (Providers, error) {
	row := q.db.QueryRowContext(ctx, createProvider, name)
	var i Providers
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
