// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.21.0
// source: stocks.sql

package postgresql

import (
	"context"
)

const createStocks = `-- name: CreateStocks :exec
INSERT INTO stocks (
    symbol, name
) VALUES (
    $1, $2
)
`

type CreateStocksParams struct {
	Symbol string `db:"symbol"`
	Name   string `db:"name"`
}

func (q *Queries) CreateStocks(ctx context.Context, arg CreateStocksParams) error {
	_, err := q.db.ExecContext(ctx, createStocks, arg.Symbol, arg.Name)
	return err
}
