postgres:
  master:
    driver: "postgres"
    # host: "127.0.0.1"
    host: "postgres"
    port: "5432"
    user: "postgres"
    name: "postgres"
    password: "password"
    sslMode: "disable"
  repricas:
    - driver: "postgres"
      # host: "reprica"
      host: "postgres"
      # port: "15432"
      port: "5432"
      user: "postgres"
      name: "postgres"
      password: "password"
      sslMode: "disable"
    - driver: "postgres"
      host: "postgres"
      port: "5432"
      user: "postgres"
      name: "postgres"
      password: "password"
      sslMode: "disable"
    - driver: "postgres"
      host: "postgres"
      port: "5432"
      user: "postgres"
      name: "postgres"
      password: "password"
      sslMode: "disable"
